// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aurelia.DotNet.VSIX.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAureliaCommandsPackageString = "dae5925d-6027-4259-b6c3-2d268e932b09";
        public static Guid guidAureliaCommandsPackage = new Guid(guidAureliaCommandsPackageString);

        public const string guidAureliaContextString = "9aab4142-64d7-45a5-87df-200680cbff35";
        public static Guid guidAureliaContext = new Guid(guidAureliaContextString);

        public const string guidAureliaAddFileCommandSetString = "cace6ee4-975d-4cd4-9742-8f7891b48285";
        public static Guid guidAureliaAddFileCommandSet = new Guid(guidAureliaAddFileCommandSetString);

        public const string guidAureliaCommandsSetString = "115e73a4-99e8-49d0-8867-360fced1b27e";
        public static Guid guidAureliaCommandsSet = new Guid(guidAureliaCommandsSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdGenerateElementAdd = 0x0100;
        public const int MyMenu = 0x1010;
        public const int MyMenuGroup = 0x1020;
        public const int CommandGroup = 0x2000;
        public const int cmdGenerateElement = 0x0100;
        public const int cmdGenerateAttribute = 0x0110;
        public const int cmdGenerateRoute = 0x0120;
    }
}