// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aurelia.DotNet.VSIX.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAureliaCommandsPackageString = "dae5925d-6027-4259-b6c3-2d268e932b09";
        public static Guid guidAureliaCommandsPackage = new Guid(guidAureliaCommandsPackageString);

        public const string guidAureliaContextString = "9aab4142-64d7-45a5-87df-200680cbff35";
        public static Guid guidAureliaContext = new Guid(guidAureliaContextString);

        public const string guidAureliaCommandsSetString = "115e73a4-99e8-49d0-8867-360fced1b27e";
        public static Guid guidAureliaCommandsSet = new Guid(guidAureliaCommandsSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdGenerateElement = 0x0100;
        public const int cmdGenerateAttribute = 0x0110;
        public const int cmdGenerateRoute = 0x0120;
        public const int cmdGenerateAureliaItem = 0x0130;
        public const int grpAureliaContext = 0x0013;
        public const int grpAureliaAdd = 0x0014;
    }
}